DROP TABLE IF EXISTS PHONES;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    id_user VARCHAR(255) IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created VARCHAR(255) NOT NULL,
    modified VARCHAR(255) NOT NULL,
    last_login VARCHAR(255) NOT NULL,
    isactive VARCHAR(5) NOT NULL
);

CREATE TABLE PHONE (
    id_phone VARCHAR(255) IDENTITY PRIMARY KEY,
    number VARCHAR(255) NOT NULL,
    city_code VARCHAR(255) NOT NULL,
    country_code VARCHAR(255) NOT NULL,
    id_user VARCHAR(255) NOT NULL,
    FOREIGN KEY(id_user) REFERENCES USER(id_user)
);

